sudo: false
language: php
php:
  - "7.1"
install:
- composer self-update
- composer --version
- composer install
script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/parallel-lint --exclude ./vendor --exclude ./test -j 256 .
  - ./vendor/bin/phpcs --standard=PSR2 --ignore=vendor,test,config,data,autoload_classmap.php --extensions=php ./
cache:
  directories:
  - vendor
  - $HOME/.composer/cache
  - node_modules
matrix:
  fast_finish: true
