sudo: false
language: php
php:
#  - "7.0"
  - "5.6"
  - "5.5"
install:
- composer self-update 1.1.2 #Travis is on the "dev" channel of composer. We want to be on stable.
- composer --version
- composer global require fxp/composer-asset-plugin --no-plugins
- composer install --prefer-dist
script:
  - find . -type d \( -path ./vendor -o -path ./test \) -prune -o -name "*.php" -print0 | xargs -0 -n1 -P8 php -l -n
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 --ignore=vendor,test,config,data,autoload_classmap.php --extensions=php ./
cache:
  directories:
  - vendor
  - $HOME/.composer/cache
  - node_modules
matrix:
  fast_finish: true
  allow_failures:
    - php: '7.0'
